# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ata_piix" "mpt3sas" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0d3d8fce-8c5d-42c5-8a0d-bcc069766566";
      fsType = "btrfs";
      options = [ "subvol=root" "compress-force=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D842-E2D3";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0d3d8fce-8c5d-42c5-8a0d-bcc069766566";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0d3d8fce-8c5d-42c5-8a0d-bcc069766566";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd" "noatime" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/0d3d8fce-8c5d-42c5-8a0d-bcc069766566";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress-force=zstd" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/0d3d8fce-8c5d-42c5-8a0d-bcc069766566";
      fsType = "btrfs";
      options = [ "subvol=log" "compress-force=zstd" "noatime" ];
      neededForBoot = true;
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  nixpkgs.hostPlatform = "x86_64-linux";
}
