[helpers]

[default]
depends = []

[default.files]
LICENSE = ""
"README.md" = ""

[default.variables]

[shell.files]
"shell/shrc" = "~/.config/shrc"
"shell/zshrc" = "~/.zshrc"

[nvim.files]
"nvim/init.lua" = "~/.config/nvim/init.lua"
